"""Корректировка в таблице

Revision ID: 1e200c5a731b
Revises: 44d4c7159b2d
Create Date: 2023-07-18 10:21:05.304728

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1e200c5a731b'
down_revision = '44d4c7159b2d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
