"""Изменение полей в таблице News

Revision ID: 44d4c7159b2d
Revises: 67fb7cb9d2b7
Create Date: 2023-07-17 18:22:36.415060

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '44d4c7159b2d'
down_revision = '67fb7cb9d2b7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
